version: '3.8'
 
services:
  redis:
    image: sloopstash/redis:v${CRM_REDIS_VERSION}
    entrypoint: /usr/bin/supervisord
    command: "-c /etc/supervisord.conf"
    volumes:
      - redis-data:/opt/redis/data
      - redis-log:/opt/redis/log
      - ${HOME_DIR}/workload/supervisor/conf/server.conf:/etc/supervisord.conf
      - ${HOME_DIR}/workload/redis/${CRM_REDIS_VERSION}/conf/supervisor.ini:/opt/redis/system/supervisor.ini
      - ${HOME_DIR}/workload/redis/${CRM_REDIS_VERSION}/conf/server.conf:/opt/redis/conf/server.conf
    networks:
      common:
        ipv4_address: ${CRM_REDIS_IP}
 
volumes:
  redis-data:
    driver: local
  redis-log:
    driver: local
 
networks:
  common:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${CRM_NETWORK}